// <auto-generated />
namespace OnlineMarketPlace.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Migration_2255 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_2255));
        
        string IMigrationMetadata.Id
        {
            get { return "202102260011462_Migration_2255"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
